version: '3.8'

services:
  codepair-server:
    build: ./server
    container_name: codepair-server
    ports:
      - "3001:3001" # API
      - "1234:1234" # WebSocket
    environment:
      - PISTON_URL=https://emkc.org/api/v2/piston/execute
    networks:
      - codepair-network

  codepair-client:
    build: ./client
    container_name: codepair-client
    ports:
      - "80:80"
    depends_on:
      - codepair-server
    networks:
      - codepair-network

networks:
  codepair-network:
    driver: bridge
